
#ifndef RENDER_HELLO_WORLD_DEFS_H
#define RENDER_HELLO_WORLD_DEFS_H

#define IMAGE_WIDTH 50
#define IMAGE_HEIGHT 50
#define IMAGE_RES_X 1000
#define IMAGE_RES_Y 1000
#define FAR_VIEW 1000
#define NEAR_VIEW 200
#define AMBIENT_LIGHT .1

#endif //RENDER_HELLO_WORLD_DEFS_H
